# Generated by Selenium IDE
import pytest
import time
import json
import os
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


def resource_path(relative_path):
		try:
				base_path = sys._MEIPASS
		except Exception:
				base_path = os.path.dirname(__file__)
		return os.path.join(base_path, relative_path)

driver = webdriver.Chrome(resource_path('./driver/chromedriver.exe'))

class TestSleepplease():
	def __init__(self):
		self.driver = driver
		self.vars = {}
	
	def teardown_method(self, method):
		self.driver.quit()
	
	def test_sleepplease(self):
		# Test name: sleep_please
		# Step # | name | target | value
		# 1 | open | /th?page=1&sort= | 
		self.driver.get("https://www.pod2you.com/th?page=1&sort=")
		# 2 | setWindowSize | 1552x840 | 
		self.driver.set_window_size(1552, 840)
		# 3 | click | css=.col-xs-3:nth-child(1) .img-responsive | 
		self.driver.find_element(By.CSS_SELECTOR, ".col-xs-3:nth-child(1) .img-responsive").click()

		### waiting for __BVID__14
		WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.ID, "__BVID__17"))).click()

		# 5 | select | id=__BVID__17 | label=Fresh Red (฿ 350.00)
		dropdown = self.driver.find_element(By.ID, "__BVID__17")
		dropdown.find_element(By.XPATH, "//option[. = 'Fresh Red (฿ 350.00)']").click()
		# 6 | click | css=.btn-cta | 
		self.driver.find_element(By.CSS_SELECTOR, ".btn-cta").click()

		### waiting for __BVID__29

		WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.ID, "__BVID__29"))).click()

		self.driver.find_element(By.ID, "__BVID__29").send_keys(Keys.CONTROL, 'a')
		self.driver.find_element(By.ID, "__BVID__29").send_keys(Keys.BACKSPACE)
		# 8 | type | id=__BVID__29 | 2
		self.driver.find_element(By.ID, "__BVID__29").send_keys(Keys.NUMPAD2)
		self.driver.find_element(By.CSS_SELECTOR, "#__BVID__29 + a").click()

		# 10 | click | linkText=สั่งซื้อสินค้าในตะกร้า | 
		WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.LINK_TEXT, "สั่งซื้อสินค้าในตะกร้า"))).click()
		# | runScript | window.scrollTo(0,200) | 
		self.driver.execute_script("window.scrollTo(0,200)")
		# 11 | click | linkText=สร้างบัญชีใหม่ที่นี่ | 
		self.driver.find_element(By.LINK_TEXT, "สร้างบัญชีใหม่ที่นี่").click()
		# 12 | click | id=firstname | 
		self.driver.find_element(By.ID, "firstname").click()
		# 13 | type | id=firstname | นาย สมชาย
		self.driver.find_element(By.ID, "firstname").send_keys("นาย สมชาย")
		# 14 | mouseDown | id=lastname | 
		element = self.driver.find_element(By.ID, "lastname")
		actions = ActionChains(self.driver)
		actions.move_to_element(element).click_and_hold().perform()
		# 15 | mouseUp | id=registerForm | 
		element = self.driver.find_element(By.ID, "registerForm")
		actions = ActionChains(self.driver)
		actions.move_to_element(element).release().perform()
		# 16 | click | id=registerForm | 
		self.driver.find_element(By.ID, "registerForm").click()
		# 17 | type | id=lastname | ชายจริงๆ
		self.driver.find_element(By.ID, "lastname").send_keys("ชายจริงๆ")

		# 21 | click | id=email | 
		self.driver.find_element(By.ID, "email").click()
		# 22 | type | id=email | 1234@hotmail.com
		self.driver.find_element(By.ID, "email").send_keys("1234@hotmail.com")
		# 21 | click | id=email | 
		self.driver.find_element(By.ID, "cemail").click()
		# 22 | type | id=email | 1234@hotmail.com
		self.driver.find_element(By.ID, "cemail").send_keys("1234@hotmail.com")
		# 27 | runScript | window.scrollTo(0,200) | 
		self.driver.execute_script("window.scrollTo(0,200)")
		# 25 | click | id=password | 
		self.driver.find_element(By.ID, "password").click()
		# 26 | type | id=password | 123456
		self.driver.find_element(By.ID, "password").send_keys("123456")
		# 27 | runScript | window.scrollTo(0,200) | 
		self.driver.execute_script("window.scrollTo(0,300)")
		# 28 | click | id=cpassword | 
		self.driver.find_element(By.ID, "cpassword").click()
		# 29 | type | id=cpassword | 123456
		self.driver.find_element(By.ID, "cpassword").send_keys("123456")
		# 30 | click | css=.form-group:nth-child(7) | 
		# self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(7)").click()
		self.driver.execute_script("document.getElementById('privacyPolicy').checked = true;")
		



	
obj = TestSleepplease()
obj.test_sleepplease()